### ISSUE TITLE
Optimal <script> tags

### ISSUE THREAD

**Issue by peterbe** [mdn/stumptown-renderer#104]
We have JS that loads like `<script src="/static/react-stuff.sj">` but we might benefit from adding `defer` and load them the `<head>` instead.
E.g. https://flaviocopes.com/javascript-async-defer/

(copied from https://github.com/mozilla/kuma/issues/5672)

**Comment by kenrick95** [comment]
I researched a bit on this issue and it seems like this is not possible without ejecting from Create React App. This is because it needs a webpack configuration change: need to insert a webpack plugin called [`script-ext-html-webpack-plugin`](https://github.com/numical/script-ext-html-webpack-plugin); and the CRA doesn't allow its users to change webpack config without ejecting.

**Comment by peterbe** [comment]
We have some control over the produced .html files in the `cli/render.js` script. It's where we get a chance to take the "template" made by CRA and make the changes we need. As a good example, this: https://github.com/mdn/stumptown-renderer/blob/71c3221de51fefb7c50195dfda9cef110692a75c/cli/render.js#L50

That makes sure that the resulting .html files have 
```html
<title>&lt;video&gt;: The Video Embed element</title>
```
for example. 

The whole HTML file is loaded into a `cheerio` instance so you could probably "pop" them, modify them (putting the `defer` attribute on) and inject them again at the bottom of the `<head>` tag. 

Would you like to try that?

**Comment by kenrick95** [comment]
Ah I see, let me try that, thanks for the guidance!
