### ISSUE TITLE
Dependabot doesn't get our workspaces

### ISSUE THREAD

**Issue by peterbe** [mdn/stumptown-renderer#215]
As we saw in https://github.com/mdn/stumptown-renderer/pull/209 Dependabot finds a/the `package.lock` (e.g. `client/package.json`) and then sees that there's no `client/yarn.lock`, so they think we fly without lock files so their PRs just update the `package.json` alone. 

Can we train Dependabot that we use yarn workspaces?

**Comment by Gregoor** [comment]
It does now!

**Comment by RongxinZhang** [comment]
@Gregoor, we have the same issue still. Not sure if have any advice.

project/
  yarn.lock <--- not updated.
  - server/
  - 
  - app/
     - package.json <--- updated by dependabot.
     - src/

**Comment by Gregoor** [comment]
sorry @RongxinZhang I don't quite remember anymore, but from reading the issue it sounds like we fixed it by configuring something in the Dependabot dashboard. Since Dependabot seems to have been fully subsumed by GitHub, that configurable info should now live somewhere within your repo's settings / insights page. Fingers crossed!

**Comment by AndysonDK** [comment]
@Gregoor @RongxinZhang 
I have pretty much the same problem, here is a working example:
https://github.com/AndysonDK/syncbase/pull/2
