### ISSUE TITLE
Automerge dependabot PRs?

### ISSUE THREAD

**Issue by Gregoor** [mdn/stumptown-renderer#255]
Wondering whether we should automerge certain dependabot PRs, given that it likes to create a lot of them. The config option allows a lot of granularity, e.g. we could automerge minor updates to dev dependencies and only automerge patch updates for the rest: https://dependabot.com/docs/config-file/#automerged_updates

Wdyt @peterbe?

**Comment by peterbe** [comment]
A concern I have is that of race conditions and potential conflicts caused to our `yarn.lock`. If we had `bors` going, we would never have this problem because no PR would be merged unless first tested one last time against `master`. 

Generally, if Dependabot makes a PR and the tests pass, I see absolutely no reason NOT to merge it (*). What could you possibly have against it? And if it passed the tests but actually broke the functionality, it's our fault for not making the tests good. Not dependabot's problem. Anyway, it's a welcome problem as general improvements to our CI is sustainable and rarely a waste of time. 

What makes me a little bit nervous is if we one day have merges to master immediately build a new production site. All automated. If upgrading a library broke something that our tests didn't catch, we could have a lot of problems on our hands. Perhaps the solution to that is to manually trigger production deployments, but have `master` merges for `stumptown-content` and `kuma-content` automatically build a production site. 

(*) Well... Dependabot will rebase its PRs automatically but what if a bot merges it too fast?

**Comment by Gregoor** [comment]
Oh right, I forgot to mention that even with the automerge option it woud only merge after it passes CI.

I'd hope Dependabot wouldn't merge something that hasn't been rebased to be up-to-date yet, but I have not found docs that confirm it.

Completely agree with you that we need to make sure our tests are good enough to prevent problems with this :+1: And also see your points around auto-prod; always build master apart from dependabot merges seems like a good approach to me.

**Comment by peterbe** [comment]
To be honest, my personal preference, considering the context, time, situation, I'd rather minimist chores (at the cost of reliability) for this project. 
So yes please, let's try this. r+

After all, this project has sub-par test coverage and it's deliberate. Many tests are there to solidify something but we don't want to solidify anything yet. We want to be fluid. And flexible. And fast.. Perhaps in a bunch of months we can backtrack on some of this rhetoric go change our stance towards other priorities.

**Comment by Gregoor** [comment]
Et voila, dependabot now automerge non-major updates. Unfortunately it doesn't rebase just before (when master diverged), so there is the possibility of two "concurrent" updates causing invalid master when they break the build in interaction (but not in isolation).

Might want to have an eye on this issue, maybe dependabot will add config for it: https://github.com/dependabot/feedback/issues/230

**Comment by Gregoor** [comment]
Oh wait nevermind, it looks it is rebasing those PRs after all. Cool!
