### ISSUE TITLE
Render BCD tables

### ISSUE THREAD

**Issue by wbamberg** [mdn/stumptown-renderer#69]
The renderer doesn't yet know how to render BCD tables from the data. This is one of the relatively complicated bits of rendering.

The result should look pretty much like the existing BCD tables on MDN (https://developer.mozilla.org/en-US/docs/Web/CSS/margin#Browser_compatibility) which is built using the [Compat.ejs](https://github.com/mdn/kumascript/blob/master/macros/Compat.ejs) KumaScript macro. So in a sense this is a port of Compat as a React component.

There are a few bits which rely on JS in the page (opening the little disclosures for compat details).

**Comment by joedarc** [comment]
I'll work on this if that's alright 👍

**Comment by wbamberg** [comment]
I'm totally OK with this if @peterbe is.

**Comment by peterbe** [comment]
@joedarc Do you have what you need to be able to start on this? 
For one thing, if the CSS gets too hairy, I would advice that you ping @schalkneethling on the CSS bits. He worked on the CSS for the refactor inside Kuma.

**Comment by joedarc** [comment]
@peterbe For now i took some of the CSS from the current BCD table on the beta site. It looks pretty close to what is on the site minus the icons. When i get the rest of the base functionality in there I'll definitely reach out to @schalkneethling to get the full CSS and it should fall into place. Where is the source for the CSS anyway? I'll also put up a draft PR soon for some feedback.

**Comment by joedarc** [comment]
![Screen Shot 2019-08-09 at 9 33 58 PM](https://user-images.githubusercontent.com/1201062/62871961-70105b00-bcea-11e9-87d6-41f96f2dd91e.png)

Currently looks like this, i updated a little more since the screenshot but it's getting there.

**Comment by peterbe** [comment]
Mind you, stumptown-renderer uses SCSS files at the moment. (We might switch to css-in-js in the future but due to legacy and ergonomics I don't want to do this until the dust has really settled). 

So when you say "took some of the CSS" you might succeed to copy the relevant SCSS definitions too.

**Comment by peterbe** [comment]
PS. @joedarc One idea I'm floating is to render the BCD tables async after document load from an XHR request. The payload to render and hydrate with the full table might be a perf drag and since it's almost always far down on the page, it serve us better to only load it in dynamically as you scroll down the page. I don't think this comment is relevant to your *progress* since the core is a good React component, but I just thought I'd share the thought.

**Comment by joedarc** [comment]
> So when you say "took some of the CSS" you might succeed to copy the relevant SCSS definitions too.

Yeah i took the CSS from the inspecting the beta page BCD table, i mainly wanted to get it to look as similar as possible so that i got it attaching the correct classes to the rendered elements and it should fall into place with the correct CSS. I put the CSS i got into the main SCSS file but that may change as this further progresses. 

> only load it in dynamically as you scroll down the page

Noted, yeah i agree with this. 

Currently i'm using vanilla JS to handle the whole "notes" portion where you click the cell and see the dropdown. I'm going to convert it to a class to get the lifecycle methods in there and set state to handle the "notes" stuff instead.

**Comment by peterbe** [comment]
> Currently i'm using vanilla JS to handle the whole "notes" portion where you click the cell and see the dropdown. I'm going to convert it to a class to get the lifecycle methods in there and set state to handle the "notes" stuff instead.

That's awesome!

The other thing we might want to do is not only to lazy load the BCD *data* but the whole React component. Then, when the component mounts, it fetches the data. That means the main bundle of JS won't have to carry the JavaScript code that you're working on. 
I.e. intersection observed --> load bcd js bundle --> XHR for bcd data --> render.
Again, I think this is premature for right now. But do keep in mind. 

Note-to-self; This is a huuuuge BCD table https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String

**Comment by joedarc** [comment]
Yeah, agree with everything you said. Right now i think my internal checklist for this is:

- Get the component feature parody
- Get the correct styles in there, adjust if necessary
- Convert the component to be a class and redo the "notes" to use state which will clean it up a good bit

When we're happy with the results of that then:
- Have some handler on the main component that tracks when to actually mount the BCD
- On mount, fetch the compatibility data, update state, that'll trigger the render to show the table

Something like that.

**Comment by peterbe** [comment]
>     * Get the component feature parody

Funny. :)

**Comment by joedarc** [comment]
Freudian slip... lol

Made more progress on this over lunch, starting to look pretty close. Going to convert it to a class and then submit a drafted PR for some preliminary review

![Screen Shot 2019-08-12 at 2 26 21 PM](https://user-images.githubusercontent.com/1201062/62888932-5719a100-bd0e-11e9-8e47-9b9ba179fcd7.png)
